[package]
name = "smart_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.10"
bincode = "1.3"  
borsh = "0.9" 
borsh-derive = "0.9"

[lib]
crate-type = ["cdylib", "lib"]
